// Rotating catchy taglines for the Durga Puja page.
// Cycles alongside song changes (index wraps automatically).
const QUOTES = [
  'Maa Asche — the whole city glows with her arrival! 🪔',
  'Dhaak er awaaz mane e Maa esche, e bochor abar utsob!',
  'Four days, infinite joy — Pujo is finally here!',
  'Where there is Durga, there is victory over every darkness.',
  'Shiuli phool o kash phool bolche — Maa asche!',
  'Pandal hopping, dhunuchi naach, and endless adda — pure Pujo magic.',
  'Ashtami er anjali, moner modhye ek notun shakti.',
  'She arrives every year to remind us: good always wins.',
  'Ekbar noy, bar bar asho Maa — amader ghore ghore.',
  'The conch shells blow, the dhaak beats — Maa Durga has arrived!',
  'Durga Puja isn\'t just a festival, it\'s a feeling that comes home.',
  'From Mahalaya to Bijoya — every moment with Maa is a blessing.',
  'Subho Mahalaya — the countdown to her homecoming begins!',
  'Maa\'s eyes hold strength enough for the whole universe.',
  'Alta rong lal, shada shari — Maa eshe geche abar bari!',
  'This Pujo, let every dhaak beat sync with your heartbeat.',
  'Ma Durga\'s smile is proof that light always finds its way.',
  'Kolkata\'s air smells like shiuli and celebration — she\'s here!',
  'Every idol tells a story of courage, grace, and homecoming.',
  'Joy Maa Durga — may her strength walk with you all year round.',
  'Ashche bochor abar hobe — but this year, we celebrate fully!',
  'Sindoor khela, dhunuchi naach, and a Maa who never truly leaves us.',
  'She rides in on her lion, and every fear quietly bows out.',
  'Pujo barshiki, notun jama, r ek mon bhora anondo.',
  'The dhunuchi smoke rises, and so does our shraddha for Maa.',
  'Bijoya\'s goodbye is never really goodbye — she returns every year.',
  'Maa Durga reminds us: strength and grace can live in the same soul.',
];
