// Durga Puja playlist — sourced from your YouTube Music "Durga Pujo" playlist.
// Streamed via YouTube's free embedded player. Edit/reorder anytime.
const SONGS = [
  { title: 'Durge Durge Durgatinashini', artist: 'Asha Bhosle', youtubeId: 'zaMxavmz2A8' },
  { title: 'Maago Anondomoye', artist: 'Avik Mukherjee', youtubeId: 'r2uDzVdj9gE' },
  { title: 'O Maa Tara Bosna Kache', artist: 'Raghab Chattopadhyay', youtubeId: 'MfW4jnXlXqU' },
  { title: 'Sobar Durga Maa', artist: 'Kumar Sanu', youtubeId: 'AdKA3o1ULmY' },
  { title: 'Om Jayatang Devi Chamunde', artist: 'Tushar Dutta', youtubeId: 'o3HccF0qviA' },
  { title: 'Jaago Maa Durga', artist: 'Indrani Bhattacherjee', youtubeId: 'JcyqxpKUYKE' },
  { title: 'Aamay Bhakti De Maa', artist: 'Parikshit Bala', youtubeId: 'VXA-YxZPnrE' },
  { title: 'Jaago Maa', artist: 'Arijit Singh', youtubeId: 'm-pcgj6y3VI' },
  { title: 'Jaago Jogmaya', artist: 'Aalo', youtubeId: '8nsgRMrILdQ' },
  { title: 'Hein Go Ma Durga', artist: 'Lopamudra Mitra', youtubeId: 'o_z_4Mg6f6M' },
  { title: 'Bolo Maa Dugga Maa', artist: 'Debolina Nandy', youtubeId: '23G77rnNdsQ' },
  { title: 'Durga Thakur Mago Tomar', artist: 'Radhika Chakraborty & Others', youtubeId: 'rfVr7gzOkLs' },
  { title: 'Gouri Elo', artist: 'Antara Nandy', youtubeId: 'Lchp6vCfbJM' },
  { title: 'Dosh Karo Noygo Maa', artist: 'Kumar Sanu', youtubeId: 'QGPtqPalT2o' },
  { title: 'O Ma Danujdalani Mahashakti', artist: 'Indrani Sen', youtubeId: '9WPKFDgTPdU' },
  { title: 'Durga Amritwani', artist: 'Madhusmita', youtubeId: 'RFWRA_rS_q8' },
  { title: 'Eseche Maa Eseche', artist: 'Papan Subhendu', youtubeId: 'Mfil82Fr3bM' },
  { title: 'Joy Maa Durga', artist: 'Raghab Chatterjee', youtubeId: 'csSTghlKwjg' },
  { title: 'Joy Joy Maa Durga', artist: 'Sathi Palui, Ankita Manna & Others', youtubeId: 'c_esxyVjSiU' },
  { title: 'Saratkale Durga Puja', artist: 'Sekhar', youtubeId: '2wf5WifXeV8' },
  { title: 'Durga Pujo Eshe Geche', artist: 'Various Artists', youtubeId: 'wZJ0dMwbL8M' },
  { title: 'Durga Puja Elo Re', artist: 'Jeetu Bhowmik', youtubeId: 'meutp82AqQs' },
  { title: 'Elo Maa Durga Maa', artist: 'Shouweick Dey', youtubeId: '2Nmn7XifvYs' },
  { title: 'Bajlo Tomar Alor Benu', artist: 'Oli and The Mystic Mouchak', youtubeId: 'dsNJWxe4U8g' },
  { title: 'O Maa Mahamaaya', artist: 'Pamela Jain / Aniruddha Rana', youtubeId: 'GD0cRnqf7YA' },
  { title: 'Duggi Elo Ghore', artist: 'Rajkumar', youtubeId: 'U_L2KqfKb_o' },
  { title: 'Pujo Alo', artist: 'Raghab Chattopadhyay', youtubeId: 'UpwSprNBMLg' },
];
